---
- name: Configure the camera module
  hosts: all
  become: true

  tasks:
    - name: Enable camera
      blockinfile:
        path: /boot/config.txt
        block: |
          start_x=1
          gpu_mem=128
    - name: Add users to video group
      user:
        name: "{{ item.name }}"
        groups: video
        append: yes
      loop: "{{ users }}"

    - name: Install motion
      apt:
        name: motion
        state: present
    - name: Add motion conf
      copy:
        src: files/camera/motion.conf
        dest: /etc/motion/motion.conf
        owner: root
        group: root
        mode: "0644"
    - name: Set /etc/default/motion
      copy:
        src: files/camera/default/motion
        dest: /etc/default/motion
        owner: root
        group: root
        mode: "0644"
    - name: Enable motion
      service:
        name: motion
        enabled: yes
