---
- name: Configure the camera module
  hosts: all
  become: true

  tasks:
    - name: Enable camera
      blockinfile:
        path: /boot/config.txt
        block: |
          start_x=1
          gpu_mem=128
    - name: Add users to video group
      user:
        name: "{{ item.name }}"
        groups: video
        append: yes
      loop: "{{ users }}"
