---
- name: Provision ssh
  hosts: all
  become: true

  tasks:
    - name: Disable password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: ^PasswordAuthentication
        line: PasswordAuthentication no
    - name: Enable public key authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: ^PubkeyAuthentication
        line: PubkeyAuthentication yes
    - name: Enable ssh
      service:
        name: ssh
        enabled: yes