---
- name: Provision users
  hosts: all
  become: true

  tasks:
    - name: Add sudo users
      user:
        name: "{{ item.name }}"
        shell: /bin/bash
        state: present
        groups: sudo
      loop: "{{ users }}"
    - name: Set ssh authorized keys from github
      authorized_key:
        user: "{{ item.name }}"
        state: present
        key: https://github.com/{{ item.github }}.keys
      loop: "{{ users }}"
    - name: Passwordless sudo
      copy:
        src: files/users/sudo-nopasswd
        dest: /etc/sudoers.d/sudo-nopasswd
        owner: root
        group: root
        mode: "0440"
