---
- hosts: all
  become: true

  tasks:
    - name: Remove default pi user
      user:
        name: "pi"
        state: absent
    - name: Add sudo users
      user:
        name: "{{ item }}"
        shell: /bin/bash
        state: present
        groups: sudo
      loop:
        - tom
        - gen