---
- name: Provision users
  hosts: all
  become: true

  vars:
    users:
      - { name: "tom", github: "treilly94" }
      - { name: "gen", github: "gmreynolds" }

  tasks:
    - name: Remove default pi user
      user:
        name: "pi"
        state: absent
    - name: Add sudo users
      user:
        name: "{{ item.name }}"
        shell: /bin/bash
        state: present
        groups: sudo
      loop: "{{ users }}"
    - name: Set ssh authorized keys from github
      authorized_key:
        user: "{{ item.name }}"
        state: present
        key: https://github.com/{{ item.github }}.keys
      loop: "{{ users }}"